/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 23 21:53:12 GMT 2020
 */

package com.br.rfs.desafio.itau.exception;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppException_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
