/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 23 21:47:56 GMT 2020
 */

package com.br.rfs.desafio.itau.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import com.br.rfs.desafio.itau.domain.DesafioResponse;
import org.springframework.http.HttpStatus;

public class DesafioResponse_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DesafioResponse<String> desafioResponse0 = new DesafioResponse<String>();
      String string0 = desafioResponse0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DesafioResponse<Object> desafioResponse0 = new DesafioResponse<Object>();
      Object object0 = desafioResponse0.getData();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DesafioResponse<String> desafioResponse0 = new DesafioResponse<String>();
      desafioResponse0.getStatusCode();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DesafioResponse<String> desafioResponse0 = new DesafioResponse<String>();
      desafioResponse0.setMessage("`b4}QB:Fw<Q~");
      String string0 = desafioResponse0.getMessage();
      assertEquals("`b4}QB:Fw<Q~", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DesafioResponse<Object> desafioResponse0 = new DesafioResponse<Object>();
      Integer integer0 = new Integer(1535);
      desafioResponse0.setData(integer0);
      Object object0 = desafioResponse0.getData();
      assertEquals(1535, object0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DesafioResponse<String> desafioResponse0 = new DesafioResponse<String>();
      desafioResponse0.setMessage("");
      String string0 = desafioResponse0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DesafioResponse<String> desafioResponse0 = new DesafioResponse<String>();
      HttpStatus httpStatus0 = HttpStatus.SWITCHING_PROTOCOLS;
      desafioResponse0.setStatusCode(httpStatus0);
      HttpStatus httpStatus1 = desafioResponse0.getStatusCode();
      assertSame(httpStatus1, httpStatus0);
  }
}
