version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  
phases:
  install:
    commands:
      - echo "Starting a new Pipeline:  stage Prepare 
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - 
  pre_build:
    commands:
      - echo initializing a new Pipeline
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo [+]Build Stage
      - mvn clean install
    finally:
      - echo build stage sucess ended
  post_build:
    commands:
      - mv target/*.jar ./
  artifacts:
    files:
      - desafio.itau-0.0.1-SNAPSHOT.jar
