version: 0.2
  
phases:
  install:
    commands:
      - echo Stage Prepare
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - 
  pre_build:
    commands:
      - echo initializing a new Pipeline
  build:
    commands:
      - mvn  install
    finally:
      - echo build stage sucess ended
  post_build:
    commands:
      - mv target/desafio.itau-0.0.1-SNAPSHOT.jar ./
