version: 0.2
phases:
  pre-build:
    commands:
    - echo "Starting the Pipeline"
     
  build:
    commands:
    - echo " Initializing build process aplication" 
    - mvn clean install
  
  post-build:
    commands:
    - echo " Starting post build phase"
    - mv target/*.jar ./