/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 23 22:03:56 GMT 2020
 */

package com.br.rfs.desafio.itau.service;

import org.junit.Test;
import static org.junit.Assert.*;
import com.br.rfs.desafio.itau.service.DesafioService;

public class DesafioService_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DesafioService desafioService0 = new DesafioService();
  }
}
