/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 23 22:03:47 GMT 2020
 */

package com.br.rfs.desafio.itau.handler;

import org.junit.Test;
import static org.junit.Assert.*;

public class StatisticsTransaction_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
