/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 23 21:45:31 GMT 2020
 */

package com.br.rfs.desafio.itau.constants;

import org.junit.Test;
import static org.junit.Assert.*;

public class RequestEntrypointConstants_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
